import type { CharacterSummaryRecord, CharacterState, MemoryRecord } from '../core/types';
import { MemoryRepository } from '../db/repositories/MemoryRepository';
import { getLogger } from '../core/logger';

/**
 * Tier 3: Character Summary - LLM-compressed personality/history summary.
 * Regenerated periodically using inference service.
 */
export class CharacterSummary {
  private log = getLogger('character-summary');

  constructor(private repo: MemoryRepository) {}

  /**
   * Get the current summary for a character, or null if none exists.
   */
  get(characterId: string, playerId: string): CharacterSummaryRecord | null {
    return this.repo.getSummary(characterId, playerId);
  }

  /**
   * Store/update a character summary (generated by LLM externally).
   */
  update(
    characterId: string,
    playerId: string,
    summary: string,
    relationshipNotes: string,
    keyFacts: string[],
  ): CharacterSummaryRecord {
    const existing = this.repo.getSummary(characterId, playerId);
    const version = (existing?.version ?? 0) + 1;

    const record = this.repo.upsertSummary({
      characterId,
      playerId,
      summary,
      relationshipNotes,
      keyFacts,
      version,
      generatedAt: Date.now(),
    });

    this.log.info({ characterId, playerId, version }, 'Character summary updated');
    return record;
  }

  /**
   * Build the prompt for LLM summary generation.
   * Called by MemoryManager when regeneration is due.
   */
  buildSummaryPrompt(
    character: CharacterState,
    recentMemories: MemoryRecord[],
    existingSummary?: CharacterSummaryRecord | null,
  ): string {
    const memoryLines = recentMemories
      .map(m => `- [${m.type}] (importance: ${m.importance}) ${m.summary}`)
      .join('\n');

    const existing = existingSummary
      ? `\nPrevious summary:\n${existingSummary.summary}\n\nPrevious relationship notes:\n${existingSummary.relationshipNotes}`
      : '';

    return `Summarize this character's current state and relationships.

Character: ${character.name} (${character.archetype})
Personality: ${character.identity.personality}
Traits: ${character.identity.traits.join(', ')}
Goals: ${character.identity.goals.join(', ')}
${existing}

Recent significant memories:
${memoryLines || '(none yet)'}

Provide a concise JSON response:
{
  "summary": "2-3 sentence overview of who this character is now and what they've been through",
  "relationshipNotes": "1-2 sentences about their relationship with the player",
  "keyFacts": ["fact1", "fact2", "fact3"]
}`;
  }
}
